config/routes.rb
Rails.application.routes.draw do
  resources :pcrs
  get 'landing/index'
  resources :pcrs do
    collection do
      post :api
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "landing#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pcr.rb
class Pcr < ApplicationRecord
  after_commit :send_partial_stats, on: [ :create, :destroy ]
  def send_partial_stats
    broadcast_update_to('landing_page', target: 'stats', partial: "landing/stats", locals: { pcrs: Pcr.all })
    # broadcast_update_to('bedno', target: 'bedno', partial: "pages/w26", locals: { bed_info: '待轉床'})
  end

  def self.special_ward_people
    where(is_special_ward: true)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @pcrs = Pcr.all
  end
end

app/controllers/pcrs_controller.rb
class PcrsController < ApplicationController
  TOKEN = "5i1z0qcOQnzKU4bhoSj9f0qoNWzIOCCHKvQSp34D"
  skip_before_action :verify_authenticity_token, only: [:api]
  before_action :authenticate, only: [:api]

  before_action :set_pcr, only: %i[ show edit update destroy ]

  # GET /pcrs or /pcrs.json
  def index
    @pcrs = Pcr.all
  end

  # GET /pcrs/1 or /pcrs/1.json
  def show
  end

  # GET /pcrs/new
  def new
    @pcr = Pcr.new
  end

  # GET /pcrs/1/edit
  def edit
  end

  # POST /pcrs or /pcrs.json
  def create
    @pcr = Pcr.new(pcr_params)

    respond_to do |format|
      if @pcr.save
        format.html { redirect_to pcr_url(@pcr), notice: "Pcr was successfully created." }
        format.json { render :show, status: :created, location: @pcr }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pcr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pcrs/1 or /pcrs/1.json
  def update
    respond_to do |format|
      if @pcr.update(pcr_params)
        format.html { redirect_to pcr_url(@pcr), notice: "Pcr was successfully updated." }
        format.json { render :show, status: :ok, location: @pcr }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pcr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pcrs/1 or /pcrs/1.json
  def destroy
    @pcr.destroy

    respond_to do |format|
      format.html { redirect_to pcrs_url, notice: "Pcr was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  # POST positive datasets from hospital imformation system
  def api
    # binding.pry
    pcr = Pcr.create! JSON.parse params[:inpatients]
    if pcr
      render json: { resultCode: 0 }, status: :ok
    else
      render json: pcr.errors, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pcr
      @pcr = Pcr.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pcr_params
      params.require(:pcr).permit(:inpatient_seq, :is_special_ward, :positived_days, :patient_no, :patient_name, :patient_idno, :ward_bed, :vs_doctor_uid, :vs_doctor_name, :admitted_at, :examined_at, :reported_at, :order_code, :examined_result)
    end

    def authenticate
      authenticate_or_request_with_http_token do |token, options|
        # Compare the tokens in a time-constant manner, to mitigate
        # timing attacks.
        ActiveSupport::SecurityUtils.secure_compare(token, TOKEN)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/pcrs_helper.rb
module PcrsHelper
end

app/views/landing/_stats.html.erb
<div class="mt-10">
  <dl class="grid grid-cols-2 gap-x-4 gap-y-8">
    <div class="border-t-2 border-gray-100 pt-6">
      <dt class="text-base font-medium text-gray-500">陽性人數</dt>
      <dd class="text-7xl font-extrabold tracking-tight text-indigo-600"><%= pcrs.all.count %></dd>
    </div>

    <div class="border-t-2 border-gray-100 pt-6">
      <dt class="text-base font-medium text-gray-500">專責病房人數</dt>
      <dd class="text-7xl font-extrabold tracking-tight text-indigo-600"><%= pcrs.special_ward_people.count %></dd>
    </div>

    <div class="border-t-2 border-gray-100 pt-6">
      <dt class="text-base font-medium text-gray-500">待轉入人數</dt>
      <dd class="text-7xl font-extrabold tracking-tight text-indigo-600">2</dd>
    </div>

    <div class="border-t-2 border-gray-100 pt-6">
      <dt class="text-base font-medium text-gray-500">待轉出人數</dt>
      <dd class="text-7xl font-extrabold tracking-tight text-indigo-600">12</dd>
    </div>
  </dl>
</div>

app/views/landing/index.html.erb
<%= turbo_stream_from "landing_page" %>
<%= t("hello", ) %>
<div class="relative bg-white">
  <div class="lg:mx-auto lg:max-w-7xl lg:px-8 lg:grid lg:grid-cols-2 lg:gap-24 lg:items-start">
    <div class="relative sm:py-16 lg:py-0">
      <div aria-hidden="true" class="hidden sm:block lg:absolute lg:inset-y-0 lg:right-0 lg:w-screen">
        <div class="absolute inset-y-0 right-1/2 w-full bg-gray-50 rounded-r-3xl lg:right-72"></div>
        <svg class="absolute top-8 left-1/2 -ml-3 lg:-right-8 lg:left-auto lg:top-12" width="404" height="392" fill="none" viewBox="0 0 404 392">
          <defs>
            <pattern id="02f20b47-fd69-4224-a62a-4c9de5c763f7" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
              <rect x="0" y="0" width="4" height="4" class="text-gray-200" fill="currentColor" />
            </pattern>
          </defs>
          <rect width="404" height="392" fill="url(#02f20b47-fd69-4224-a62a-4c9de5c763f7)" />
        </svg>
      </div>
      <div class="relative mx-auto max-w-md px-4 sm:max-w-3xl sm:px-6 lg:px-0 lg:max-w-none lg:py-20">
        <div class="relative pt-64 pb-10 rounded-2xl shadow-xl overflow-hidden">
          <%= image_tag "https://cdn.pixabay.com/photo/2021/02/03/23/09/hallway-5979689_1280.jpg", class:"absolute inset-0 h-full w-full object-cover" %>
          <div class="absolute inset-0 mix-blend-multiply"></div>
          <div class="absolute inset-0 bg-gradient-to-t opacity-70"></div>
          <div class="relative px-8">
            <blockquote class="mt-8">
              <div class="relative text-lg font-medium text-gray-100 md:flex-grow">
                <svg class="absolute top-0 left-0 transform -translate-x-3 -translate-y-2 h-8 w-8 text-indigo-400" fill="currentColor" viewBox="0 0 32 32" aria-hidden="true">
                  <path d="M9.352 4C4.456 7.456 1 13.12 1 19.36c0 5.088 3.072 8.064 6.624 8.064 3.36 0 5.856-2.688 5.856-5.856 0-3.168-2.208-5.472-5.088-5.472-.576 0-1.344.096-1.536.192.48-3.264 3.552-7.104 6.624-9.024L9.352 4zm16.512 0c-4.8 3.456-8.256 9.12-8.256 15.36 0 5.088 3.072 8.064 6.624 8.064 3.264 0 5.856-2.688 5.856-5.856 0-3.168-2.304-5.472-5.184-5.472-.576 0-1.248.096-1.44.192.48-3.264 3.456-7.104 6.528-9.024L25.864 4z" />
                </svg>
                <p class="relative">
                  DevOps（Development和Operations的組合詞）是一種重視「軟體開發人員（Dev）」和「IT運維技術人員（Ops）」之間溝通合作的文化、運動或慣例。通過自動化「軟體交付」和「架構變更」的流程，來使得構建、測試、發布軟體能夠更加地快捷、頻繁和可靠<%= link_to '- 維基百科', 'https://zh.wikipedia.org/zh-tw/DevOps' %>
                </p>
              </div>
              <footer class="mt-4">
                <span class="flex justify-end text-base font-semibold text-white" >Photo@<%= link_to "Simplified Pixabay License", "https://pixabay.com/service/license/", class:"text-base font-semibold text-indigo-200" %> </span>
              </footer>
            </blockquote>
          </div>
        </div>
      </div>
    </div>

    <div class="relative mx-auto max-w-md px-4 sm:max-w-3xl sm:px-6 lg:px-0">
      <!-- Content area -->
      <div class="pt-24 sm:pt-16 lg:pt-32">
        <h2 class="text-3xl text-gray-900 font-extrabold tracking-tight sm:text-4xl">
          Digital Transformation X 
        </h2>
        <h2 class="text-3xl text-indigo-600 font-extrabold tracking-tight sm:text-4xl">
          Hospital Wards
        </h2>
        <div class="mt-6 text-gray-500 space-y-6">
          <p class="text-lg">
          </p>
          <%# <p class="text-base leading-7">
            Sollicitudin tristique eros erat odio sed vitae, consequat turpis elementum. Lorem nibh vel, eget pretium arcu vitae. Eros eu viverra donec ut volutpat donec laoreet quam urna. Sollicitudin tristique eros erat odio sed vitae, consequat turpis elementum. Lorem nibh vel, eget pretium arcu vitae. Eros eu viverra donec ut volutpat donec laoreet quam urna.
          </p>
          <p class="text-base leading-7">
            Rhoncus nisl, libero egestas diam fermentum dui. At quis tincidunt vel ultricies. Vulputate aliquet velit faucibus semper. Pellentesque in venenatis vestibulum consectetur nibh id. In id ut tempus egestas. Enim sit aliquam nec, a. Morbi enim fermentum lacus in. Viverra.
          </p> %>
        </div>
      </div>

      <!-- Stats -->
      <div id="stats">
        <%= render "stats", pcrs: @pcrs %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XWards</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-20 px-5">
      <%= yield %>
    </main>
  </body>
  <%= render "shared/footer" %>
</html>

app/views/pcrs/_form.html.erb
<%= form_with(model: pcr, class: "contents") do |form| %>
  <% if pcr.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(pcr.errors.count, "error") %> prohibited this pcr from being saved:</h2>

      <ul>
        <% pcr.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :inpatient_seq %>
    <%= form.text_field :inpatient_seq, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :is_special_ward %>
    <%= form.check_box :is_special_ward, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :positived_days %>
    <%= form.number_field :positived_days, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :patient_no %>
    <%= form.text_field :patient_no, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :patient_name %>
    <%= form.text_field :patient_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :patient_idno %>
    <%= form.text_field :patient_idno, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :ward_bed %>
    <%= form.text_field :ward_bed, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :vs_doctor_uid %>
    <%= form.text_field :vs_doctor_uid, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :vs_doctor_name %>
    <%= form.text_field :vs_doctor_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :admitted_at %>
    <%= form.datetime_field :admitted_at, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :examined_at %>
    <%= form.datetime_field :examined_at, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :reported_at %>
    <%= form.datetime_field :reported_at, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :order_code %>
    <%= form.text_field :order_code, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :examined_result %>
    <%= form.text_field :examined_result, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/pcrs/_pcr.html.erb
<div id="<%= dom_id pcr %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Inpatient seq:</strong>
    <%= pcr.inpatient_seq %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Is special ward:</strong>
    <%= pcr.is_special_ward %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Positived days:</strong>
    <%= pcr.positived_days %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Patient no:</strong>
    <%= pcr.patient_no %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Patient name:</strong>
    <%= pcr.patient_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Patient idno:</strong>
    <%= pcr.patient_idno %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Ward bed:</strong>
    <%= pcr.ward_bed %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Vs doctor uid:</strong>
    <%= pcr.vs_doctor_uid %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Vs doctor name:</strong>
    <%= pcr.vs_doctor_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Admitted at:</strong>
    <%= pcr.admitted_at %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Examined at:</strong>
    <%= pcr.examined_at %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Reported at:</strong>
    <%= pcr.reported_at %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Order code:</strong>
    <%= pcr.order_code %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Examined result:</strong>
    <%= pcr.examined_result %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this pcr", pcr, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this pcr', edit_pcr_path(pcr), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/pcrs/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing pcr</h1>

  <%= render "form", pcr: @pcr %>

  <%= link_to "Show this pcr", @pcr, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to pcrs", pcrs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pcrs/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Pcrs</h1>
    <%= link_to 'New pcr', new_pcr_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="pcrs" class="min-w-full">
    <%= render @pcrs %>
  </div>
</div>

app/views/pcrs/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New pcr</h1>

  <%= render "form", pcr: @pcr %>

  <%= link_to 'Back to pcrs', pcrs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pcrs/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @pcr %>

    <%= link_to 'Edit this pcr', edit_pcr_path(@pcr), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this pcr', pcr_path(@pcr), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to pcrs', pcrs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-white">
  <div class="max-w-7xl mx-auto py-12 px-4 overflow-hidden sm:px-6 lg:px-8">
    <nav class="-mx-5 -my-2 flex flex-wrap justify-center" aria-label="Footer">
      <div class="px-5 py-2">
        <%= link_to t('about'), root_path%>
      </div>

      <div class="px-5 py-2">
        <%= link_to t('blog'), root_path%>
      </div>

      <div class="px-5 py-2">
        <%= link_to t('jobs'), root_path%>
      </div>

    </nav>
    <div class="mt-8 flex justify-center space-x-6">
      <a href="#" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">Facebook</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd" />
        </svg>
      </a>

      <a href="#" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">Instagram</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd" />
        </svg>
      </a>

      <a href="#" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">Twitter</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
        </svg>
      </a>

      <a href="#" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">GitHub</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
        </svg>
      </a>

      <a href="#" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">Dribbble</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path fill-rule="evenodd" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10c5.51 0 10-4.48 10-10S17.51 2 12 2zm6.605 4.61a8.502 8.502 0 011.93 5.314c-.281-.054-3.101-.629-5.943-.271-.065-.141-.12-.293-.184-.445a25.416 25.416 0 00-.564-1.236c3.145-1.28 4.577-3.124 4.761-3.362zM12 3.475c2.17 0 4.154.813 5.662 2.148-.152.216-1.443 1.941-4.48 3.08-1.399-2.57-2.95-4.675-3.189-5A8.687 8.687 0 0112 3.475zm-3.633.803a53.896 53.896 0 013.167 4.935c-3.992 1.063-7.517 1.04-7.896 1.04a8.581 8.581 0 014.729-5.975zM3.453 12.01v-.26c.37.01 4.512.065 8.775-1.215.25.477.477.965.694 1.453-.109.033-.228.065-.336.098-4.404 1.42-6.747 5.303-6.942 5.629a8.522 8.522 0 01-2.19-5.705zM12 20.547a8.482 8.482 0 01-5.239-1.8c.152-.315 1.888-3.656 6.703-5.337.022-.01.033-.01.054-.022a35.318 35.318 0 011.823 6.475 8.4 8.4 0 01-3.341.684zm4.761-1.465c-.086-.52-.542-3.015-1.659-6.084 2.679-.423 5.022.271 5.314.369a8.468 8.468 0 01-3.655 5.715z" clip-rule="evenodd" />
        </svg>
      </a>
    </div>
  </div>
</footer>